### ISSUE TITLE
Feature Request: Add Prism Tile

### ISSUE THREAD

**Issue by farscapian** [clams-tech/Remote#247]
The [BOLT12 Prism plugin](https://github.com/gudnuf/bolt12-prism) has undergone additional development and is reaching a stable state. Assuming the prism plugin is installed, Clams Remote should allow a node owner to create and manage prisms by surfacing a "Prism" tile. The UI should also enable the node operator to attach a prism to a BOLT12 offer and enable prism payment via `prism-pay`.
 @evansmj

**Comment by evansmj** [comment]
The idea is to check if `plugin list` returns `/bolt12-prism`.  If it does, we display a new Tile like this: 

<img width="1104" alt="Screenshot 2024-04-28 at 12 58 46 PM" src="https://github.com/clams-tech/Remote/assets/11140095/0a69ec77-3cd7-4ec7-b8f8-89b266e3082f">

Then we will display a screen where the user can configure a Prism.  And then bind it to an Offer.  All of this UI will be in the Prisms page.  If a user does not have Prisms installed, no prism ui will be seen.

**Comment by evansmj** [comment]
fyi I am workin on this feature

**Comment by johngribbin** [comment]
@evansmj Hey Michael 

how is your progress coming along? Would be happy to review when you think its ready

**Comment by evansmj** [comment]
hey @johngribbin, we got a quick demo for our hackathon.  I need to clean up some alignments and make the prism detail part look more like rest of the app.  we did get a prism icon from a designer (need to size it better).  here are some preliminary screenshots.  if you have design feedback that would be great and i could match whatever you like.  

A prism tile will be shown only if the plugins list returns prisms.  it renders before Settings so that settings remains the last tile.  
<img width="1723" alt="Screenshot 2024-05-04 at 3 18 52 PM" src="https://github.com/clams-tech/Remote/assets/11140095/6


The prism portal will show a list of prisms, and a list of offers.  A user will be able to Bind a prism to an existing offer here.  I show the list of offers here so that all prism related code remains in the prism portal.  I haven't figured out the ux for setting a Binding yet.  
<img width="1726" alt="Screenshot 2024-05-04 at 3 19 01 PM" src="https://github.com/clams-tech/Remote/assets/11140095/1f8b6444-a5a0-4872-ab13-1a6912f8b6de">
3f5867d-df0c-4a50-a5d3-9da0e067ebb7">

Now if you click on a prism it will show the prism details.  This layout is up in the air and I think i should match offers/channels.
<img width="1728" alt="Screenshot 2024-05-04 at 3 19 08 PM" src="https://github.com/clams-tech/Remote/assets/11140095/345454ae-4cbe-4caf-98fc-35cf78e44f14">



The prism detail reflects this json

```
[
  {
    "id": "prism1",
    "timestamp": 1714796059,
    "outlay_factor": 0.8,
    "prism_members": [
      {
        "member_id": "f892a60f-83c0-4df9-9b62-674ada641d4b",
        "label": "Carol",
        "destination": "lno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrc2qajx2enpw4k8g93pq0hqest8tsj7m2k4k7s7q5ukeq0rtlrv6kpprhe3hxjs0rx6cg6hz",
        "split": 1,
        "fees_incurred_by": "remote",
        "payout_threshold": "0msat"
      },
      {
        "member_id": "deba7e02-baef-4ed5-9c1d-809f3fe023bf",
        "label": "Dave",
        "destination": "03cb5a8d446d7e6e5c86df9999ffa77bc2a4be24b30a3f374976057671531dd24f",
        "split": 1,
        "fees_incurred_by": "remote",
        "payout_threshold": "0msat"
      },
      {
        "member_id": "25a745a5-eb6c-4d6c-b5c4-f9e90aa2a81e",
        "label": "Erin",
        "destination": "lno1qgsqvgnwgcg35z6ee2h3yczraddm72xrfua9uve2rlrm9deu7xyfzrc2qajx2enpw4k8g93pqtyguvz38rkv44hgxhhnjdsgf04vj35ualp3pv9tqqamwwjeacc9s",
        "split": 1,
        "fees_incurred_by": "remote",
        "payout_threshold": "0msat"
      }
    ]
  }
]
```


prism bindings will reflect this data.

```
{
   "bolt12_prism_bindings": [
      {
         "offer_id": "ecbb23dd33aeea4ca3c9198bdf459b004b455f13bbe72554be15a5aab4100ce6",
         "prism_id": "prism1",
         "timestamp": 1714760131,
         "member_outlays": {
            "2503e139-760c-48fc-90f0-66e88780ece4": "0msat",
            "03d6c054-2593-462d-9f68-4fd81bc0aa28": "0msat",
            "091a8fe9-a8bc-48ae-8fba-7ac33ebd961b": "0msat"
         }
      }
   ]
}
```

Somewhere i need to figure out a place to show existing Bindings.  Maybe this should be separate from the offers list.  Any design ideas would be great else I'll keep working with Farscapian to create it

**Comment by farscapian** [comment]
Just going to throw this out there after chatting about this topic with a few folks. It would be preferable to make the prism-binding stuff be centered around BOLT12 Offers in the UI. That is, the place you go to bind a prism and to view binding outlays would be Top Menu -> Offers. @evansmj I know this contradicts what I told you during the hackathon, but in speaking with @johngribbin , it may make sense to keep that stuff under Offers (the prism-related stuff under Offers would still be contingent on plugin-list). Keep in mind binding stuff is keyed on offer_id in the Prism API/db.

So in term of UI, on on the Menu -> Prism, replace the "Offers" Section (on the lower half) with a button or link that states "Manage Bindings" that links you to Menu -> Offers. When a user clicks an offer, they will see the prism_id if any prism bound to the offer. When creating a binding, the UI will display a list of Prism_ids, of which one (and only one) prism can be selected.

**Comment by evansmj** [comment]
Sounds good on moving the bindings to the offers.  for binding_id i think yes you could remove it since i will latch these bindings onto existing offer_ids

**Comment by johngribbin** [comment]
Hey @farscapian 

I am working on this now. Will drop any Qs I have here for discussion as I work through the feature.

**Comment by farscapian** [comment]
@johngribbin , you're the man.  pulling @sbddesign, who expressed interest in the project, into the conversation.
